### ISSUE TITLE
Additional listener options feature

### ISSUE THREAD

**Issue by eazuka** [ikkez/f3-events#1]
Hello @ikkez 
I have a question regarding the additional listener options example below:
```
$events->on('user_login', function($username,$context,$event){
  \Flash::addMessage('You have logged in successfully', $event['options']['type']);
}, 20, array('type'=>'success'));
```
from your example above, what is this part supposed to do?

`$event['options']['type']`

`array('type'=>'success')`

**Comment by ikkez** [comment]
You can set custom options to a listener, and when the listener is called, you can use that defined options for anything you like. In this context, a notification listener is hooked on the user_login event, with the option `type: success`, which than can be used in the listener, to i.e. make the notification box in green color or something.

**Comment by eazuka** [comment]
thanks for the response.
