### ISSUE TITLE
\Event already declared.

### ISSUE THREAD

**Issue by ionutforyou** [ikkez/f3-events#2]
After firing F3 core and an \Event::instance I get method not found.
Dumping declared classes I get a previously defined Event class.
  ```
228 => "ZMQDeviceException"
  229 => "Event"
  230 => "EventBase"
  231 => "EventConfig"
  232 => "EventBufferEvent"
  233 => "EventBuffer
```

I see I had PECL extension Event installed, disabled it and is ok, but any other recommandation would be appreciated.

**Comment by ikkez** [comment]
fixed in the latest release. New namespace is now `\Sugar\Event` instead.
